Repository kaltura/playkit-js-providers, pull requests merged in 2018-06, with the labels that each got.

#48 feat: analytics service
  dist/playkit-analytics-service.js
  dist/playkit-analytics-service.js.map
  src/k-provider/ovp/services/analytics/analytics-service.js
  src/k-provider/ovp/services/analytics/index.js
  test/src/k-provider/ovp/services/analytics-service.spec.js
  webpack.config.js
Labels: Type: Feature

#56 fix: add "/api_v3" to default service URL
  src/k-provider/ovp/config.js
Labels: Type: Bug

#57 fix(FEC-8316): protect against invalid server response
  src/util/request-builder.js
Labels: Type: Feature

#55 feat(FEC-8046): 360 Support
  flow-typed/types/media-config-sources.js
  src/k-provider/ott/provider.js
  src/k-provider/ovp/provider-parser.js
  src/k-provider/ovp/provider.js
  src/k-provider/ovp/response-types/kaltura-media-entry.js
  test/src/k-provider/ott/media-config-data.js
  test/src/k-provider/ovp/media-config-data.js
Labels: Priority: High, Type: Feature

#58 feat(FEC-8331): expose the anonymous flag on session object
  src/k-provider/ott/provider.js
  src/k-provider/ovp/provider.js
  test/src/k-provider/ott/media-config-data.js
  test/src/k-provider/ovp/media-config-data.js
  test/src/k-provider/ovp/provider.spec.js
Labels: Type: Feature
