Repository kaltura/playkit-js-providers, pull requests merged in 2018-12, with the labels that each got.

#72 feat(FEC-8730): add kaltura regex action support to providers
  src/k-provider/common/response-types/kaltura-access-control-modify-request-host-regex-action.js
  src/k-provider/ovp/config.js
  src/k-provider/ovp/provider-parser.js
  src/k-provider/ovp/response-types/kaltura-playback-context.js
  test/src/k-provider/ovp/be-data.js
  test/src/k-provider/ovp/media-config-data.js
  test/src/k-provider/ovp/provider.spec.js
Labels: Priority: High, Type: Bug

#71 fix(FEC-8739): block action is not fired from OTT provider
  src/entities/media-format.js
  src/k-provider/common/base-provider-parser.js
  src/k-provider/ott/loaders/asset-loader.js
  src/k-provider/ott/provider-parser.js
  src/k-provider/ott/provider.js
  src/k-provider/ott/response-types/kaltura-playback-context.js
  src/k-provider/ott/response-types/kaltura-rule-action.js
  src/k-provider/ovp/loaders/media-entry-loader.js
  src/k-provider/ovp/provider-parser.js
  src/k-provider/ovp/provider.js
  src/k-provider/ovp/response-types/kaltura-access-control-modify-request-host-regex-action.js
  src/k-provider/ovp/response-types/kaltura-playback-context.js
  src/k-provider/ovp/response-types/kaltura-rule-action.js
  test/src/k-provider/ott/be-data.js
  test/src/k-provider/ott/provider.spec.js
  test/src/k-provider/ovp/be-data.js
  test/src/k-provider/ovp/provider.spec.js
Labels: Priority: High, Type: Bug

#70 feat(FEC-8734): add protection for invalid source creation
  src/k-provider/common/base-provider-parser.js
  src/k-provider/ott/provider-parser.js
  src/k-provider/ovp/play-source-url-builder.js
  src/k-provider/ovp/provider-parser.js
  test/src/k-provider/ovp/playback-sources-data.js
  test/src/k-provider/ovp/provider-parser.spec.js
Labels: Type: Feature

#74 feat(FEC-8766): add closed captions from multi request to external
  flow-typed/types/caption-type.js
  flow-typed/types/env-config.js
  flow-typed/types/external-caption-object.js
  flow-typed/types/media-config-sources.js
  flow-typed/types/media-sources.js
  src/entities/media-sources.js
  src/k-provider/ovp/config.js
  src/k-provider/ovp/external-captions-builder.js
  src/k-provider/ovp/loaders/media-entry-loader.js
  src/k-provider/ovp/provider-parser.js
  src/k-provider/ovp/provider.js
  src/k-provider/ovp/response-types/kaltura-caption-list.js
  src/k-provider/ovp/services/captions-service.js
Labels: Priority: High, Type: Feature
