Repository kaltura/playkit-js-providers, pull requests merged in 2019-01, with the labels that each got.

#75 feat(FEC-8746): add wid parameter with the OVP provider
  flow-typed/types/provider-options.js
  src/k-provider/common/base-provider.js
  src/k-provider/ovp/loaders/session-loader.js
  src/k-provider/ovp/provider.js
  src/k-provider/ovp/services/session-service.js
  test/src/k-provider/ovp/provider.spec.js
Labels: Priority: High, Type: Feature

#76 feat: support external media sources for Youtube
  src/k-provider/ovp/provider-parser.js
  src/k-provider/ovp/request-params/base-entry-response-profile.js
  src/k-provider/ovp/response-types/kaltura-media-entry.js
  test/src/k-provider/ovp/provider-parser-data.js
  test/src/k-provider/ovp/provider-parser.spec.js
Labels: Type: Feature

#77 chore: fix flow
  flow-typed/types/provider-options.js
Labels: Priority: High, Type: Bug

#78 feat(FEC-8816): support the new captions API structure in getPlaybackContext
  .github/PULL_REQUEST_TEMPLATE.md
  flow-typed/types/env-config.js
  src/k-provider/ovp/config.js
  src/k-provider/ovp/external-captions-builder.js
  src/k-provider/ovp/loaders/media-entry-loader.js
  src/k-provider/ovp/provider-parser.js
  src/k-provider/ovp/response-types/kaltura-caption-list.js
  src/k-provider/ovp/services/captions-service.js
  test/src/k-provider/ovp/provider-parser-data.js
Labels: Priority: Medium, Type: Feature

#79 fix(FEC-8858): the captions in languages list displayed twice
  src/k-provider/ovp/external-captions-builder.js
Labels: Priority: High, Type: Bug

#81 feat(FEC-8875): when an external caption format is DFXP return the webvtt url
  src/k-provider/ovp/external-captions-builder.js
  test/src/k-provider/ovp/external-captions-builder.spec.js
Labels: Priority: High, Type: Feature
